export { CounterButtonPage } from './CounterButtonPage'
export { HomePage } from './HomePage'
export { PeopleListPage } from './PeopleListPage'
export { NotFound } from './404'
export { ProtectedPage } from './ProtectedPage'
export { ControlledFormPage } from './ControlledFormPage'
export { UncontrolledFormPage } from './UncontrolledFormPage'
